# -*- coding: utf-8 -*-
# Deployment settings for TestGame.
# This file is autogenerated by the mkb system and used by the s3e deployment
# tool during the build process.

config = {}
cmdline = ['C:/Marmalade/7.0/s3e/makefile_builder/mkb.py', 'c:/Users/Enelar/Documents/GitHub/TestGame/TestGame.mkb', '--buildenv=VC11X', '--fake-vc-call', '--default-buildenv=vc11x', '--msvc-project', '--deploy-only']
mkb = 'c:/Users/Enelar/Documents/GitHub/TestGame/TestGame.mkb'
mkf = ['c:\\marmalade\\7.0\\modules\\iwutil\\iwutil.mkf', 'c:\\marmalade\\7.0\\modules\\third_party\\libjpeg\\libjpeg.mkf', 'c:\\marmalade\\7.0\\modules\\third_party\\libpng\\libpng.mkf', 'c:\\marmalade\\7.0\\modules\\third_party\\zlib\\zlib.mkf', 'c:\\marmalade\\7.0\\modules\\iwgl\\iwgl.mkf', 'c:\\marmalade\\7.0\\modules\\third_party\\cocos2dx\\cocos2dx\\proj.marmalade\\cocos2dx.mkf', 'c:\\marmalade\\7.0\\modules\\third_party\\cocos2dx\\cocos2dx\\platform\\third_party\\marmalade\\libxml2.mkf', 'c:\\marmalade\\7.0\\modules\\third_party\\cocos2dx\\cocos2dx\\platform\\third_party\\marmalade\\freetype.mkf', 'c:\\marmalade\\7.0\\modules\\third_party\\cocos2dx\\cocos2dx\\platform\\third_party\\marmalade\\libtiff\\libtiff.mkf', 'c:\\marmalade\\7.0\\modules\\third_party\\cocos2dx\\external\\box2d\\proj.marmalade\\box2d.mkf']

class DeployConfig(object):
    pass

######### ASSET GROUPS #############

assets = {}

assets['Default'] = [
    ('c:/Users/Enelar/Documents/GitHub/TestGame\data', '.', 0),
]

######### DEFAULT CONFIG #############

class DefaultConfig(DeployConfig):
    embed_icf = -1
    name = 'TestGame'
    pub_sign_key = 0
    priv_sign_key = 0
    caption = 'TestGame'
    long_caption = 'TestGame'
    version = [0, 0, 1]
    config = ['c:/Users/Enelar/Documents/GitHub/TestGame/data/app.icf']
    data_dir = 'c:/Users/Enelar/Documents/GitHub/TestGame/data'
    iphone_link_lib = []
    wp8_ext_managed_dll = []
    linux_ext_lib = []
    android_extra_application_manifest = []
    iphone_link_libdir = []
    iphone_link_libdirs = []
    iphone_link_opts = []
    android_external_jars = []
    android_external_res = []
    android_supports_gl_texture = []
    android_extra_manifest = []
    wp8_ext_native_dll = []
    win32_ext_dll = []
    android_so = []
    osx_ext_dll = []
    tizen_so = []
    wp8_ext_capabilities = []
    iphone_link_libs = []
    target = {
         'gcc_x86' : {
                   'debug'   : r'c:/Users/Enelar/Documents/GitHub/TestGame/build_testgame_vc11x/Debug_TestGame_VC11X_gcc_x86/TestGame.so',
                   'release' : r'c:/Users/Enelar/Documents/GitHub/TestGame/build_testgame_vc11x/Release_TestGame_VC11X_gcc_x86/TestGame.so',
                 },
         'mips_gcc' : {
                   'debug'   : r'c:/Users/Enelar/Documents/GitHub/TestGame/build_testgame_vc11x/Debug_TestGame_VC11X_gcc_mips/TestGame.so',
                   'release' : r'c:/Users/Enelar/Documents/GitHub/TestGame/build_testgame_vc11x/Release_TestGame_VC11X_gcc_mips/TestGame.so',
                 },
         'arm_gcc' : {
                   'debug'   : r'c:/Users/Enelar/Documents/GitHub/TestGame/build_testgame_vc11x/Debug_TestGame_VC11X_gcc_arm/TestGame.s3e',
                   'release' : r'c:/Users/Enelar/Documents/GitHub/TestGame/build_testgame_vc11x/Release_TestGame_VC11X_gcc_arm/TestGame.s3e',
                 },
         'mips' : {
                   'debug'   : r'c:/Users/Enelar/Documents/GitHub/TestGame/build_testgame_vc11x/Debug_TestGame_VC11X_gcc_mips/TestGame.so',
                   'release' : r'c:/Users/Enelar/Documents/GitHub/TestGame/build_testgame_vc11x/Release_TestGame_VC11X_gcc_mips/TestGame.so',
                 },
         'gcc_x86_android' : {
                   'debug'   : r'c:/Users/Enelar/Documents/GitHub/TestGame/build_testgame_vc11x/Debug_TestGame_VC11X_gcc_x86_android/TestGame.so',
                   'release' : r'c:/Users/Enelar/Documents/GitHub/TestGame/build_testgame_vc11x/Release_TestGame_VC11X_gcc_x86_android/TestGame.so',
                 },
         'arm' : {
                   'debug'   : r'c:/Users/Enelar/Documents/GitHub/TestGame/build_testgame_vc11x/Debug_TestGame_VC11X_arm/TestGame.s3e',
                   'release' : r'c:/Users/Enelar/Documents/GitHub/TestGame/build_testgame_vc11x/Release_TestGame_VC11X_arm/TestGame.s3e',
                 },
         'x86' : {
                   'debug'   : r'c:/Users/Enelar/Documents/GitHub/TestGame/build_testgame_vc11x/Debug_TestGame_VC11X_x86/TestGame.s86',
                   'release' : r'c:/Users/Enelar/Documents/GitHub/TestGame/build_testgame_vc11x/Release_TestGame_VC11X_x86/TestGame.s86',
                 },
        }
    assets = assets['Default']

default = DefaultConfig()
